server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/my_test_db?serverTimeZone=UTC
      username: root
      password: root
  cache:
    type: redis
    redis:
      use-key-prefix: true #前缀 value
      cache-null-values: false # 是否缓存 Null 值
      key-prefix: sms_ # 使用二次前缀
      time-to-live: 10s # 生存周期
  redis:
    host: localhost
    port: 6379



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto

